<fieldset>

    <div id="filterBar" style="text-align:center">
        <a href="#tablaResult" onClick="consultar('A')"> A |</a>
        <a href="#tablaResult" onClick="consultar('B')"> B |</a>
        <a href="#tablaResult" onClick="consultar('C')"> C |</a>
        <a href="#tablaResult" onClick="consultar('D')"> D |</a>
        <a href="#tablaResult" onClick="consultar('E')"> E |</a>
        <a href="#tablaResult" onClick="consultar('F')"> F |</a>
        <a href="#tablaResult" onClick="consultar('G')"> G |</a>
        <a href="#tablaResult" onClick="consultar('H')"> H |</a>
        <a href="#tablaResult" onClick="consultar('I')"> I |</a>
        <a href="#tablaResult" onClick="consultar('j')"> J |</a>
        <a href="#tablaResult" onClick="consultar('K')"> K |</a>
        <a href="#tablaResult" onClick="consultar('L')"> L |</a>
        <a href="#tablaResult" onClick="consultar('M')"> M |</a>
        <a href="#tablaResult" onClick="consultar('N')"> N |</a>
        <a href="#tablaResult" onClick="consultar('O')"> O |</a>
        <a href="#tablaResult" onClick="consultar('P')"> P |</a>
        <a href="#tablaResult" onClick="consultar('Q')"> Q |</a>
        <a href="#tablaResult" onClick="consultar('R')"> R |</a>
        <a href="#tablaResult" onClick="consultar('S')"> S |</a>
        <a href="#tablaResult" onClick="consultar('T')"> T |</a>
        <a href="#tablaResult" onClick="consultar('U')"> U |</a>
        <a href="#tablaResult" onClick="consultar('V')"> V |</a>
        <a href="#tablaResult" onClick="consultar('W')"> W |</a>
        <a href="#tablaResult" onClick="consultar('X')"> X |</a>
        <a href="#tablaResult" onClick="consultar('Y')"> Y |</a>
        <a href="#tablaResult" onClick="consultar('Z')"> Z |</a>
        <a href="#tablaResult" onClick="consultar('TODOS')"> [% "TODOS" | i18n %] </a>
    </div><br>
    <input type="checkbox" name="habilitados_filter" id="habilitados_filter"> [% "Mostrar s&oacute;lo usuarios habilitados"| i18n %]
</fieldset>