
<div id="pager" name="paginador" class="pager" >
<form>
	<img class="first" src="<!-- TMPL_VAR NAME='themelang' -->/includes/jquery/tablesorter/pager/first.png"/>
	<img class="prev" src="<!-- TMPL_VAR NAME='themelang' -->/includes/jquery/tablesorter/pager/prev.png"/>
	<input class="pagedisplay" type="text"/>
	<img class="next" src="<!-- TMPL_VAR NAME='themelang' -->/includes/jquery/tablesorter/pager/next.png"/>
	<img class="last" src="<!-- TMPL_VAR NAME='themelang' -->/includes/jquery/tablesorter/pager/last.png"/>
	<select class="pagesize">
		<option value="10" selected="selected">10</option>
		<option value="20">20</option>
		<option value="50">50</option>
	</select>
</form>
</div>