<!--
 list of Classes to be included en /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">Libros Sencillos o de Dibujos
<option value="ER">F&aacute;cil Lectura	
<option value="JNF">No-Ficci&oacute;n para chicos 
<option value="JF">Ficci&oacute;n para chicos
<option value="TREF">Referencia de Maestro
<option value="FYA">Ficci&oacute;n para j&oacute;venes adultos	
<option value="REF">Libros de Referencia
<option value="F">Ficci&oacute;n
<option value="NF">No Ficci&oacute;n
<option value="CD">Disco Compacto
<!--	<option value="E|ER">Easy Books-->

