
<html>
<head>
<title>Biblioteca - Facultad de Ciencias Econ&oacute;micas - U.N.L.P.</title>


</head>
<link rel="stylesheet" type="text/css" href="<!-- TMPL_VAR name="themelang" -->/includes/opac.css">
<body>



<!--HDL Colours

        Yellow = ffcc00 
        light blue = ccccff
        bright blue links = 0000ff
        aubergine = 663266 
        light green/grey = cccc99


-->

<!------------------------MENUS-------------------------------->

<table cellpadding=0 cellspacing=0 width="100%" border=0>


<tr class="tope">

        <td valign=bottom width="90"><img src="<!-- TMPL_VAR NAME='themelang' -->/images/inside-top-join.gif"
        width=80 height=50 alt="KOHA: &Aacute;rea de Miembros" hspace=0 vspace=0 border=0></td>
        <td><h1><!-- TMPL_VAR Name="pagetitle" --></h1></td>
        
        <td align="right">
        <a href="[% url_prefix %]/opac-search.pl">
        <img src="<!-- TMPL_VAR NAME='themelang' -->/images/menu-search.png" alt="Buscar" hspace=0 vspace=0 border=0 name="menu-search">
        </a>
        
        <a href="/join.html">
        <img src="<!-- TMPL_VAR NAME='themelang' -->/images/menu-join.png"
        alt="Registrarse" hspace=0 vspace=0 border=0 name="menu-join"></a>

        <a href="[% url_prefix %]/opac-main.pl">
        <img src="<!-- TMPL_VAR NAME='themelang' -->/images/menu-home.png"
        alt="Inicio" hspace=0 vspace=0 border=0 name="menu-home"></a></td>

         <td width="15">&nbsp; <td>
        </TR>



<tr valign=top>

        <td><img src="<!-- TMPL_VAR name='themelang' -->/images/inside-koha-bottom.gif" 
	width=80  height=50 alt="KOHA" hspace=0 vspace=0 border=0 ></td>

        <td align=right><img src="<!-- TMPL_VAR name='themelang' -->/images/holder.gif"
	width=300 height=48 alt="" hspace=0 vspace=0 name="mouseover" ></a></td>

        </TR>



</TABLE>



<!-------------------------MAIN BODY OF PAGE-------------------------->
<BLOCKQUOTE>
