
<script type="text/javascript">

    // MENSAJES PARA USUARIOS

    PASSWORDS_DISTINTAS = "[% 'Las claves son distintas, ingreselas nuevamente.' | i18n %]";

    PASSWORD_EN_BLANCO = "[% 'Las clave no puede estar en blanco, ingreselas nuevamente.' | i18n %]";

    LAS_CLAVES_SON_DISTINTAS= "[% 'Las claves son distintas. Ingreselas nuevamente.' | i18n %]";

    CAMBIO_DE_CONTRASENIA= "[% 'Cambio de Contraseña' | i18n %]";

    ESTA_SEGURO_QUE_DESEA_RESERVAR= '[% "Realmente desea reservar el ejemplar?" | i18n %]';

    ESTA_SEGURO_QUE_DESEA_CANCELAR_RESERVA= '[% "Realmente desea cancelar la reserva?" | i18n %]';

    FAVORITE_ADDED= '[% "Se agrego el favorito correctamente." | i18n %]';

    FAVORITE_ADDED_ERROR= '[% "No se pudo agregar el favorito" | i18n %]';

    FAVORITE_DELETED= '[% "Se elimino el favorito correctamente." | i18n %]';

    FAVORITE_CONFIRM_DELETE= '[% "Desea borrar el favorito?" | i18n %]';

    FAVORITE_DELETED_ERROR= '[% "No se pudo eliminar el favorito" | i18n %]';

    CATALOGO_TITLE= '[% "Alerta de Catalogo" | i18n %]';

    OPAC_ALERT_TITLE= '[% "Alerta de La Biblioteca" | i18n %]';
    ARRASTRAR_IMAGEN = "[% 'Arrastre para subir la imagen' | i18n %]";
    SUBIR_IMAGEN = "[% 'Seleccionar imagen' | i18n %]";
    POR_FAVOR_INGRESE_SU_APELLIDO   = "[% 'Por favor, ingrese su apellido' | i18n %]";
    POR_FAVOR_INGRESE_SU_NOMBRE     = "[% 'Por favor, ingrese su/s nombre/s' | i18n %]";
    POR_FAVOR_INGRESE_SU_MENSAJE    = "[% 'Por favor, ingrese su mensaje' | i18n %]";
    POR_FAVOR_INGRESE_UNA_DIR_DE_EMAIL_VALIDA= "[% 'Por favor, ingrese una direcci\u00f3n de email v\u00e1lida' | i18n %]";
    
    POR_FAVOR_INGRESE_DEPARTAMENTO= "[% 'Por favor, ingrese un departamento' | i18n %]";
    
    SEGURO_OCULTAR_NOVEDAD="[% 'Esta seguro que quiere ocultar esta novedad?' | i18n %]";

    //Mensajes para recomendaciones

    POR_FAVOR_INGRESE_UN_AUTOR = "[% 'Por favor, ingrese un autor' | i18n %]";
    POR_FAVOR_INGRESE_UN_TITULO = "[% 'Por favor, ingrese un titulo' | i18n %]";
    POR_FAVOR_INGRESE_UNA_EDICION = "[% 'Por favor, ingrese una edicion' | i18n %]";
    POR_FAVOR_INGRESE_UNA_EDITORIAL = "[% 'Por favor, ingrese una editorial' | i18n %]";
    POR_FAVOR_INGRESE_UNA_CANTIDAD = "[% 'Por favor, ingrese una cantidad v\u00e1lida' | i18n %]";
    POR_FAVOR_INGRESE_UN_MOTIVO = "[% 'Por favor, ingrese un motivo' | i18n %]";

    /*=================================================File Uploader=========================================================*/
    TYPE_ERROR  = " Error en {file}: Solamente se permiten extensiones {extensions}";
    SIZE_ERROR  = "{file} es muy grande, el maximo tama&ntilde;o es {sizeLimit}.";
    EMPTY_ERROR = "{file} esta vacio. Elija un archivo con contenido, por favor.";
    ON_LEAVE    = "[% 'The files are being uploaded, if you leave now the upload will be cancelled.' | i18n %]";  
     /*=================================================Fin File Uploader=========================================================*/

</script>
