<!-- Content unit - One column -->
        <h1 class="block">3 - Tables</h1>
        <div class="column1-unit">
          <table>
            <tr><th class="top" scope="col">Heading 1</th><th class="top" scope="col">Heading 2</th><th class="top" scope="col">Heading 3</th><th class="top" scope="col">Heading 4</th></tr>
            <tr><th scope="row">Category 1</th><td>Data</td><td>Data</td><td>Data</td></tr>
            <tr><th scope="row">Category 2</th><td>Data</td><td>Data</td><td>Data</td></tr>
            <tr><th scope="row">Category 3</th><td>Data</td><td>Data</td><td>Data</td></tr>
          </table>
          <p class="caption"><strong>Table x.x.</strong> Caption</p>
        </div>          