<link href="/includes/css/aloha.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/includes/require.js"></script>
<script type="text/javascript" src="/includes/aloha/aloha.js"
                     data-aloha-plugins="common/ui,
                                          common/format,
                                          common/list,
                                          common/link,
                                          common/highlighteditables">
</script>
 
<script type="text/javascript">
       Aloha.ready( function() {
              var $ = Aloha.jQuery;
              $('.editable_wysiwyg').aloha();
       });
</script>   