<script type="text/javascript">

//VARIABLES PARA ui.datepicker.js
CLOSE_TEXT = "[% 'Cerar' | i18n %]";
CLOSE_STATUS = "[% 'Close without change'| i18n %]";
CLEAR_TEXT = "[% 'Limpiar' | i18n %]";
CLEAR_STATUS = "[% 'Borrar la fecha actual' | i18n %]";
CURRENT_TEXT = "[% 'Hoy' | i18n %]";
CURRENT_STATUS = "[% 'Mostrar mes actual' | i18n %]";
NEXT_TEXT = "[% 'Siguiente' | i18n %]";
NEXT_STATUS = "[% 'Mostrar el siguiente mes' | i18n %]";
MONTH_STATUS = "[% 'Mostrar un mes diferente' | i18n %]";
YEAR_STATUS = "[% 'Mostrar un año diferente' | i18n %]";
WEEK_HEADER = "[% 'Smna' | i18n %]";
WEEK_STATUS = "[% 'Semana del mes' | i18n %]";
DAY_STATUS = "[% 'Primer día de la semana' | i18n %]";
DATE_STATUS = "[% 'Seleccione DD/MM/d' | i18n %]";
PREV_TEXT = "[% 'Anterior' | i18n %]";
PREV_STATUS= "[% 'Mostrar la fecha anterior' | i18n %]";
DATE_STATUS = "[% 'Seleccione Dia/Mes/Año' | i18n %]";
INIT_STATUS = "[% 'Seleccione una fecha' | i18n %]";
DATE_FORMAT = "[% 'dd/mm/yy' | i18n %]";
SHOW_PREVIOUS = "[% 'Mostrar anterior' | i18n %]";
SHOW_NEXT = "[% 'Mostrar siguiente' | i18n %]";
SHOW_DIFERENT = "[% 'Mostrar uno diferente' | i18n %]";


LOADING_RESULTS = "[% 'Cargando resultados' | i18n %]";
OF = "[% 'de' | i18n %]";
// END VARIABLES PARA ui.datepicker.js

//Para DataTables

S_LENGTH_MENU= '[% "Mostrar _MENU_ registros por pagina" | i18n %]';
S_ZERO_RECORDS= '[% "No se encontraron coincidencias"| i18n %]';
S_INFO= '[% "Mostrando _START_ a _END_ registros" | i18n %]';
S_INFO_EMPTY= '[% "Mostrando 0 a 0 registros" | i18n %]';
S_INFO_FILTERED= '[% "(filtrados de _MAX_ registros totales)" | i18n %]';
S_SEARCH= '[% "Filtrar" | i18n %]: ';


//FIN PARA CALENDAR
CANCELAR= '[% "Cancelar" | i18n %]';
OK= '[% "Ok" | i18n %]';
EDITABLE_MSG= '[% "Editar..." | i18n %]';

</script>