
<!-- Librerias necesarias para manejar el WindowHelper -->
<link type="text/css" href="[% temas %]/default/includes/windowHelper.css"      rel="stylesheet" />
<link type="text/css" href="/includes/jquery/ui/base/jquery.ui.dialog.css"      rel="stylesheet" />



<!--  
<link type="text/css" href="/includes/jquery/ui/base/jquery.ui.core.css"        rel="stylesheet" />
<link type="text/css" href="/includes/jquery/ui/base/jquery.ui.theme.css"       rel="stylesheet" />

-->

<script type="text/javascript" src="/includes/jquery/ui/core-min.js"></script>
<script type="text/javascript" src="/includes/jquery/ui/widget-min.js"></script>
<script type="text/javascript" src="/includes/jquery/ui/mouse-min.js"></script>
<script type="text/javascript" src="/includes/jquery/ui/draggable-min.js"></script>
<script type="text/javascript" src="/includes/jquery/ui/position-min.js"></script>
<script type="text/javascript" src="/includes/jquery/ui/resizable-min.js"></script>
<script type="text/javascript" src="/includes/jquery/ui/dialog-min.js"></script>
