use EconoV3 ;
GRANT SELECT on cat_nivel3 to opac@localhost identified by'opac'; 
GRANT SELECT on  cat_analitica                      to opac@localhost; 
GRANT SELECT on  cat_autor                          to opac@localhost; 
GRANT SELECT on  cat_autor_analitica                to opac@localhost; 
GRANT SELECT on  cat_colaborador                    to opac@localhost; 
GRANT SELECT on  cat_contenido_estante              to opac@localhost; 
GRANT SELECT on  cat_control_seudonimo_autor        to opac@localhost; 
GRANT SELECT on  cat_control_seudonimo_editorial    to opac@localhost; 
GRANT SELECT on  cat_control_seudonimo_tema         to opac@localhost; 
GRANT SELECT on  cat_control_sinonimo_autor         to opac@localhost; 
GRANT SELECT on  cat_control_sinonimo_editorial     to opac@localhost; 
GRANT SELECT on  cat_control_sinonimo_tema          to opac@localhost; 
GRANT SELECT on  cat_editorial                      to opac@localhost; 
GRANT SELECT on  cat_encabezado_campo_opac          to opac@localhost; 
GRANT SELECT on  cat_encabezado_item_opac           to opac@localhost; 
GRANT SELECT on  cat_estante                        to opac@localhost; 
GRANT SELECT on  cat_estructura_catalogacion        to opac@localhost; 
GRANT SELECT on  cat_estructura_catalogacion_opac   to opac@localhost; 
GRANT SELECT on  cat_historico_disponibilidad       to opac@localhost; 
GRANT SELECT on  cat_nivel1                         to opac@localhost; 
GRANT SELECT on  cat_nivel1_repetible               to opac@localhost; 
GRANT SELECT on  cat_nivel2                         to opac@localhost; 
GRANT SELECT on  cat_nivel2_repetible               to opac@localhost; 
GRANT SELECT on  cat_nivel3                         to opac@localhost; 
GRANT SELECT on  cat_nivel3_repetible               to opac@localhost; 
GRANT SELECT on  cat_pref_mapeo_koha_marc           to opac@localhost; 
GRANT SELECT on  cat_ref_colaborador                to opac@localhost; 
GRANT SELECT on  cat_ref_tipo_nivel3                to opac@localhost; 
GRANT SELECT on  cat_tema                           to opac@localhost; 
GRANT SELECT on  cat_tema_analitica                 to opac@localhost; 
GRANT SELECT on  circ_prestamo                      to opac@localhost; 
GRANT SELECT on  circ_ref_tipo_prestamo             to opac@localhost; 
GRANT SELECT on  circ_regla_sancion                 to opac@localhost; 
GRANT SELECT on  circ_regla_tipo_sancion            to opac@localhost; 
GRANT SELECT, INSERT, UPDATE, DELETE on  circ_reserva                       to opac@localhost; 
GRANT SELECT on  circ_sancion                       to opac@localhost; 
GRANT SELECT on  circ_tipo_prestamo_sancion         to opac@localhost; 
GRANT SELECT on  circ_tipo_sancion                  to opac@localhost; 
GRANT SELECT on  pref_categoria_unidad_informacion  to opac@localhost; 
GRANT SELECT on  pref_estructura_campo_marc         to opac@localhost; 
GRANT SELECT on  pref_estructura_subcampo_marc      to opac@localhost; 
GRANT SELECT on  pref_feriado                       to opac@localhost; 
GRANT SELECT on  pref_informacion_referencia        to opac@localhost; 
GRANT SELECT on  pref_iso2709                       to opac@localhost; 
GRANT SELECT on  pref_palabra_frecuente             to opac@localhost; 
GRANT SELECT on  pref_preferencia_sistema           to opac@localhost; 
GRANT SELECT on  pref_relacion_unidad_informacion   to opac@localhost; 
GRANT SELECT on  pref_servidor_z3950                to opac@localhost; 
GRANT SELECT on  pref_tabla_referencia              to opac@localhost; 
GRANT SELECT on  pref_tabla_referencia_info         to opac@localhost; 
GRANT SELECT on  pref_unidad_informacion            to opac@localhost; 
GRANT SELECT on  pref_valor_autorizado              to opac@localhost; 
GRANT SELECT on  ref_disponibilidad                 to opac@localhost; 
GRANT SELECT on  ref_dpto_partido                   to opac@localhost; 
GRANT SELECT on  ref_estado                         to opac@localhost; 
GRANT SELECT on  ref_idioma                         to opac@localhost; 
GRANT SELECT on  ref_localidad                      to opac@localhost; 
GRANT SELECT on  ref_nivel_bibliografico            to opac@localhost; 
GRANT SELECT on  ref_pais                           to opac@localhost; 
GRANT SELECT on  ref_provincia                      to opac@localhost; 
GRANT SELECT on  ref_soporte                        to opac@localhost; 
GRANT SELECT on  ref_tipo_operacion                 to opac@localhost; 
GRANT SELECT, INSERT on  rep_busqueda                       to opac@localhost; 
GRANT SELECT, INSERT on  rep_historial_busqueda             to opac@localhost; 
GRANT SELECT, INSERT on  rep_historial_circulacion          to opac@localhost; 
GRANT SELECT on  rep_historial_prestamo             to opac@localhost; 
GRANT SELECT on  rep_historial_sancion              to opac@localhost; 
GRANT SELECT on  rep_registro_modificacion          to opac@localhost; 
GRANT SELECT, INSERT, UPDATE, DELETE on  sist_sesion                        to opac@localhost; 
GRANT SELECT on  usr_estado                         to opac@localhost; 
GRANT SELECT on  usr_permiso                        to opac@localhost; 
GRANT SELECT, UPDATE on  usr_persona                        to opac@localhost; 
GRANT SELECT on  usr_ref_categoria_socio            to opac@localhost; 
GRANT SELECT on  usr_ref_estado                     to opac@localhost; 
GRANT SELECT on  usr_ref_tipo_documento             to opac@localhost; 
GRANT SELECT, UPDATE on  usr_socio                          to opac@localhost; 
GRANT SELECT on  usr_socio_relacionado              to opac@localhost; 
GRANT SELECT on  z3950queue                         to opac@localhost; 
GRANT SELECT on  z3950results                       to opac@localhost; 
GRANT SELECT on  perm_general to opac@localhost; 
GRANT SELECT on  perm_circulacion to opac@localhost; 
GRANT SELECT on  perm_reporte to opac@localhost; 
GRANT SELECT on  perm_catalogo to opac@localhost; 
GRANT SELECT on  cat_portada_registro to opac@localhost; 
